namespace BiddingSystem.Application.DTOs.BidDtos
{
    // Response DTO for bid documents
    public class BidDocumentDto
    {
        public int Id { get; set; }
        public string DocumentType { get; set; }
        public string FileName { get; set; }
        public DateTime UploadDate { get; set; }
        public string DownloadUrl { get; set; } // Will be generated by controller
    }
}
